# This is a config for E2B sandbox template.
# You can use template ID (mtdsg7h23yuhtoipflsd) or template name (vibe-nextjs-test-omkumarjha2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-test-omkumarjha2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test-omkumarjha2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test-omkumarjha2')

team_id = "e69aee54-9ec3-45ce-a9dd-96484fa67a97"
start_cmd = "/compile_page.sh"
dockerfile = "sandbox-templates\\nextjs\\e2b.Dockerfile"
template_name = "vibe-nextjs-test-omkumarjha2"
template_id = "mtdsg7h23yuhtoipflsd"
